# =============================================================================
# ceng384_helpers.py — CENG 384 FFT Ocean Waves Homework
# Plotting utilities, test-surface generators, validators, and visualizers.
# Students do NOT edit this file.
# =============================================================================

import numpy as np
import matplotlib.pyplot as plt
from time import perf_counter


# ─────────────────────────────────────────────────────────────────────────────
# Section 1 — Core Utility Helpers
# ─────────────────────────────────────────────────────────────────────────────

def plot_surface_3d(Z, title="Ocean surface", L=10.0, stride=1, zlim=None):
    Z = np.real(np.asarray(Z))
    Ny, Nx = Z.shape

    x = np.linspace(-L/2, L/2, Nx)
    y = np.linspace(-L/2, L/2, Ny)
    X, Y = np.meshgrid(x, y)

    fig = plt.figure(figsize=(9, 6))
    ax = fig.add_subplot(111, projection="3d")

    surf = ax.plot_surface(
        X, Y, Z,
        cmap="ocean",
        edgecolor="none",
        linewidth=0,
        antialiased=True,
        rstride=stride,
        cstride=stride
    )

    ax.set_title(title)
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_zlabel("height")

    if zlim is not None:
        ax.set_zlim(*zlim)

    ax.view_init(elev=35, azim=-60)
    fig.colorbar(surf, ax=ax, shrink=0.6, aspect=12, label="height")
    plt.show()


def relative_error(a, b):
    a = np.asarray(a)
    b = np.asarray(b)
    return np.linalg.norm(a - b) / (np.linalg.norm(b) + 1e-12)


def is_power_of_two(N):
    return N > 0 and (N & (N - 1)) == 0


# ─────────────────────────────────────────────────────────────────────────────
# Section 2 — Frequency / Wavenumber Grid Helpers (used by Tasks 5–7)
# ─────────────────────────────────────────────────────────────────────────────

def _frequency_indices(N):
    """DFT bin indices: [0, 1, …, N/2-1, -N/2, …, -1] for even N."""
    return np.concatenate([np.arange(0, N // 2), np.arange(-N // 2, 0)])


def _make_wavenumber_grid(N, L=10.0):
    """Return KX, KY grids in rad/unit-length for an L-by-L domain."""
    k = 2 * np.pi * _frequency_indices(N) / L
    return np.meshgrid(k, k)


# ─────────────────────────────────────────────────────────────────────────────
# Section 3 — Test Surface Generator
# ─────────────────────────────────────────────────────────────────────────────

def make_ocean_surface(N=64, L=10.0, seed=0, target_std=0.12):
    """
    Build a calm 2D surface by summing low-frequency 2D sinusoids.
    This function does not use FFT; it only creates a test surface.
    """
    rng = np.random.default_rng(seed)

    x = np.arange(N)
    y = np.arange(N)
    X, Y = np.meshgrid(x, y)

    Z = np.zeros((N, N), dtype=float)

    components = [
        (2, 1), (1, 3), (3, 2), (-1, 2),
        (2, -1), (1, 1), (-2, 3), (3, -1)
    ]

    for fx, fy in components:
        amp = rng.uniform(0.05, 0.18)
        phi = rng.uniform(0, 2 * np.pi)
        Z += amp * np.cos(2 * np.pi * (fx * X / N + fy * Y / N) + phi)

    std = np.std(Z)
    if std > 1e-12:
        Z = Z / std * target_std

    return Z


def centered_2d(A):
    """fftshift-like centering for visualisation only."""
    A = np.asarray(A)
    return np.roll(np.roll(A, A.shape[0] // 2, axis=0), A.shape[1] // 2, axis=1)


def plot_2d_spectrum(H, title="2D magnitude spectrum"):
    mag = np.log1p(np.abs(centered_2d(H)))
    plt.figure(figsize=(6, 5))
    plt.imshow(mag, cmap="magma", origin="lower")
    plt.colorbar(label="log(1 + |H[kx,ky]|)")
    plt.title(title)
    plt.xlabel("centered kx bin")
    plt.ylabel("centered ky bin")
    plt.show()


# ─────────────────────────────────────────────────────────────────────────────
# Section 4 — Task Validators
# ─────────────────────────────────────────────────────────────────────────────

def validate_task1(my_dft, my_idft):
    """
    Task 1.2 — Validate the student's my_dft / my_idft against numpy's FFT.
    Call as:  validate_task1(my_dft, my_idft)
    """
    print("=" * 45)
    print("Task 1.2 Validation — DFT / IDFT")
    print("=" * 45)

    test_cases = {
        "Impulse":       np.array([1, 0, 0, 0, 0, 0, 0, 0]),
        "Constant (DC)": np.ones(8),
        "Sine Wave":     np.sin(2 * np.pi * 2 * np.linspace(0, 1, 8, endpoint=False)),
        "Random Noise":  np.random.default_rng(42).normal(size=16),
    }

    all_pass = True
    for name, x in test_cases.items():
        X_student = my_dft(x)
        X_ref     = np.fft.fft(x)
        dft_pass  = np.allclose(X_student, X_ref, atol=1e-10)

        x_student = my_idft(X_student)
        idft_pass = np.allclose(x_student, x, atol=1e-10)

        status = "PASS" if (dft_pass and idft_pass) else "FAIL"
        if status == "FAIL":
            all_pass = False
        print(f"  {name:15s}: {status}")

    print()
    if all_pass:
        print("All Task 1 tests passed.")
    else:
        print("Some Task 1 tests FAILED — check your implementation.")


def validate_task3(my_fft, my_ifft):
    """
    Task 3.4 — Validate the student's my_fft / my_ifft against numpy's FFT.
    Call as:  validate_task3(my_fft, my_ifft)
    """
    print("=" * 45)
    print("Task 3.4 Validation — FFT / IFFT")
    print("=" * 45)

    rng = np.random.default_rng(42)
    all_pass = True

    for N_test in [2, 4, 8, 16, 64, 128]:
        x         = rng.normal(size=N_test) + 1j * rng.normal(size=N_test)
        X_student = my_fft(x)
        X_ref     = np.fft.fft(x)
        fft_err   = np.max(np.abs(X_student - X_ref))

        x_recon   = my_ifft(X_student)
        recon_err = np.max(np.abs(x_recon - x))

        status = "PASS" if fft_err < 1e-8 and recon_err < 1e-8 else "FAIL"
        if status == "FAIL":
            all_pass = False
        print(f"  N={N_test:4d}  {status}")

    # Known-signal checks
    print()
    print("Known-signal checks:")

    x_imp = np.zeros(8); x_imp[0] = 1.0
    imp_ok = np.allclose(my_fft(x_imp), np.ones(8))
    print(f"  Impulse  → all-ones spectrum : {'PASS' if imp_ok else 'FAIL'}")
    if not imp_ok:
        all_pass = False

    x_dc = np.ones(8)
    X_dc = my_fft(x_dc)
    dc_ok = np.isclose(X_dc[0], 8.0) and np.allclose(X_dc[1:], 0, atol=1e-10)
    print(f"  DC       → spike at k=0      : {'PASS' if dc_ok else 'FAIL'}")
    if not dc_ok:
        all_pass = False

    print()
    if all_pass:
        print("All Task 3 tests passed.")
    else:
        print("Some Task 3 tests FAILED — check your implementation.")


def validate_task4(my_fft2, my_ifft2):
    """
    Task 4.3 — Validate the student's my_fft2 / my_ifft2.
    Call as:  validate_task4(my_fft2, my_ifft2)
    """
    print("=" * 45)
    print("Task 4.3 Validation — 2D FFT / IFFT")
    print("=" * 45)

    rng = np.random.default_rng(42)
    all_pass = True

    for size in [4, 8, 16, 32]:
        A         = rng.normal(size=(size, size)) + 1j * rng.normal(size=(size, size))
        A_student = my_fft2(A)
        A_ref     = np.fft.fft2(A)
        fft_err   = np.max(np.abs(A_student - A_ref))

        A_recon   = my_ifft2(A_student)
        recon_err = np.max(np.abs(A_recon - A))

        status = "PASS" if fft_err < 1e-8 and recon_err < 1e-8 else "FAIL"
        if status == "FAIL":
            all_pass = False
        print(f"  {size:2d}×{size:2d}  {status}")

    print()
    if all_pass:
        print("All Task 4 tests passed.")
    else:
        print("Some Task 4 tests FAILED — check your implementation.")


# ─────────────────────────────────────────────────────────────────────────────
# Section 5 — Task Visualizers
# ─────────────────────────────────────────────────────────────────────────────

def _time_function(fn, x, repeats=3):
    times = []
    for _ in range(repeats):
        start = perf_counter()
        fn(x)
        times.append(perf_counter() - start)
    return min(times)


def run_timing_comparison(my_dft, make_signal):
    """
    Task 2 — Plot runtime of my_dft vs. numpy FFT on a log-log scale.
    Call as:  run_timing_comparison(my_dft, make_signal)
    """
    Ns = [16, 32, 64, 128, 256, 512, 1024]
    dft_times, npfft_times = [], []

    for N in Ns:
        x = make_signal(1, N=N)
        dft_times.append(_time_function(my_dft, x, repeats=2))
        npfft_times.append(_time_function(np.fft.fft, x, repeats=5))

    plt.figure(figsize=(8, 4))
    plt.loglog(Ns, dft_times,   marker="o", label="my_dft  (O(N²))")
    plt.loglog(Ns, npfft_times, marker="o", label="np.fft.fft (reference)")
    plt.xlabel("N")
    plt.ylabel("time [s]")
    plt.title("Runtime motivation for the FFT")
    plt.grid(True, which="both", alpha=0.3)
    plt.legend()
    plt.show()

    print(f"{'N':>6}  {'my_dft':>12}  {'np.fft':>12}")
    print("-" * 34)
    for N, td, tf in zip(Ns, dft_times, npfft_times):
        print(f"{N:6d}  {td:.6f} s  {tf:.6f} s")


def visualize_task4(my_fft2, my_ifft2):
    """
    Task 4.4 — 2D spectrum + reconstructed surface visualisation.
    Call as:  visualize_task4(my_fft2, my_ifft2)
    """
    N = 32
    X_grid, Y_grid = np.meshgrid(np.arange(N), np.arange(N))

    Z = 2 * np.sin(6 * np.pi * X_grid / N) + 0.2 + np.sin(4 * np.pi * Y_grid / N)

    Z_fft   = my_fft2(Z)
    Z_recon = my_ifft2(Z_fft)

    fig = plt.figure(figsize=(18, 6))

    Z_fft_shifted = np.fft.fftshift(Z_fft)
    ax1 = fig.add_subplot(121)
    im  = ax1.imshow(np.abs(Z_fft_shifted), cmap="magma",
                     extent=[-N // 2, N // 2, -N // 2, N // 2])
    ax1.set_title("2D FFT Magnitude\n(Spectral Peaks)")
    plt.colorbar(im, ax=ax1, fraction=0.046, pad=0.04)

    ax2 = fig.add_subplot(122, projection="3d")
    ax2.plot_surface(X_grid, Y_grid, Z_recon.real, cmap="ocean",
                     edgecolor="none", linewidth=0, cstride=1)
    ax2.set_title("Reconstructed Surface")

    plt.tight_layout()
    plt.show()


def animate_task5(Z, moving_surface, L=10.0):
    """
    Task 5.3 — Animate a drifting ocean surface.
    Call as:  animate_task5(Z, moving_surface)
    """
    from matplotlib.animation import FuncAnimation
    from IPython.display import HTML

    N = Z.shape[0]
    x = np.linspace(0, L, N, endpoint=False)
    y = np.linspace(0, L, N, endpoint=False)
    X_grid, Y_grid = np.meshgrid(x, y)

    fig = plt.figure(figsize=(8, 6))
    ax  = fig.add_subplot(111, projection="3d")

    Z0   = moving_surface(Z, L=L, t=0.0, theta_deg=30.0, speed=0.4)
    surf = [ax.plot_surface(X_grid, Y_grid, Z0, cmap="viridis", edgecolor="none")]

    ax.set_xlim(0, L); ax.set_ylim(0, L); ax.set_zlim(-0.5, 0.5)
    ax.set_xlabel("x"); ax.set_ylabel("y"); ax.set_zlabel("height")

    def _update(frame):
        t  = frame * 0.1
        Zt = moving_surface(Z, L=L, t=t, theta_deg=30.0, speed=0.4)
        surf[0].remove()
        surf[0] = ax.plot_surface(X_grid, Y_grid, Zt, cmap="viridis", edgecolor="none")
        ax.set_title(f"Drifting ocean surface   t = {t:.2f} s")
        return surf

    anim = FuncAnimation(fig, _update, frames=60, interval=100, blit=False)
    return HTML(anim.to_jshtml())


def visualize_task6(my_fft2, filter_surface):
    """
    Task 6.3 — Apply three filter modes and display results.
    Call as:  visualize_task6(my_fft2, filter_surface)
    """
    N, L = 64, 10.0
    rng  = np.random.default_rng(99)
    Xg, Yg = np.meshgrid(np.arange(N), np.arange(N))

    Z_sea = np.zeros((N, N))
    for fx, fy, amp in [(1,2,0.30),(2,1,0.28),(1,-1,0.25),(-2,3,0.22)]:
        Z_sea += amp * np.cos(2*np.pi*(fx*Xg + fy*Yg)/N + rng.uniform(0, 2*np.pi))
    for fx, fy in [(7,5),(8,6),(-6,8),(9,-7)]:
        Z_sea += 0.12 * np.cos(2*np.pi*(fx*Xg + fy*Yg)/N + rng.uniform(0, 2*np.pi))
    for fx, fy in [(18,12),(19,14),(-16,18),(20,-15),(17,19)]:
        Z_sea += 0.06 * np.cos(2*np.pi*(fx*Xg + fy*Yg)/N + rng.uniform(0, 2*np.pi))

    plot_2d_spectrum(my_fft2(Z_sea), title="Task 6: spectrum of the multi-band surface")
    plot_surface_3d(Z_sea, title="Task 6: original multi-band surface", L=L, zlim=(-0.8, 0.8))

    Z_low,  mask_low  = filter_surface(Z_sea, mode="low",  cutoff=4)
    Z_high, mask_high = filter_surface(Z_sea, mode="high", cutoff=14)
    Z_band, mask_band = filter_surface(Z_sea, mode="band", low=5,  high=13)

    fig, axes = plt.subplots(1, 3, figsize=(14, 4))
    for ax, mask, title in zip(
        axes,
        [mask_low, mask_high, mask_band],
        ["Low-pass mask (cutoff=4)", "High-pass mask (cutoff=14)", "Band-pass mask (5–13)"]
    ):
        ax.imshow(centered_2d(mask), cmap="gray", origin="lower")
        ax.set_title(title)
        ax.set_xlabel("centered kx")
        ax.set_ylabel("centered ky")
    plt.tight_layout()
    plt.show()

    plot_surface_3d(Z_low,  title="Task 6: low-pass filtered",  L=L, zlim=(-0.8, 0.8))
    plot_surface_3d(Z_high, title="Task 6: high-pass filtered", L=L, zlim=(-0.8, 0.8))
    plot_surface_3d(Z_band, title="Task 6: band-pass filtered", L=L, zlim=(-0.8, 0.8))


def visualize_task7(add_ripple, downsample2d, antialias_downsample, filter_surface):
    """
    Task 7.3 — Compare direct vs. anti-aliased downsampling.
    Call as:  visualize_task7(add_ripple, downsample2d, antialias_downsample, filter_surface)
    """
    Z_base   = make_ocean_surface(N=64, L=10.0, seed=12)
    Z_ripple = add_ripple(Z_base, amplitude=0.06, fx=19, fy=15)

    factor   = 2
    Z_direct = downsample2d(Z_ripple, factor=factor)
    Z_aa     = antialias_downsample(Z_ripple, factor=factor)

    plot_surface_3d(Z_ripple, title="Task 7: original surface + high-freq ripple", L=10.0, zlim=(-0.5, 0.5))
    plot_surface_3d(Z_direct, title="Task 7: direct decimation by 2",              L=10.0, zlim=(-0.5, 0.5))
    plot_surface_3d(Z_aa,     title="Task 7: antialias then decimate",             L=10.0, zlim=(-0.5, 0.5))

    print("Original shape         :", Z_ripple.shape)
    print("After decimation shape :", Z_direct.shape)

    N = Z_ripple.shape[0]
    expected_cutoff = N // (2 * factor)
    Z_ref, _ = filter_surface(Z_ripple, mode="low", cutoff=expected_cutoff)
    Z_ref_ds = downsample2d(Z_ref, factor)
    err = relative_error(Z_aa, Z_ref_ds)
    print(f"Relative error vs reference (cutoff={expected_cutoff}): {err:.2e}")
    if err < 1e-10:
        print("antialias_downsample correctness check: PASS")
    else:
        print("antialias_downsample correctness check: FAIL — check your cutoff")
